# ports
server:
  port: 8080

# spring configs
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true

# logging settings
logging:
  level:
    com.casumo: DEBUG
